### ISSUE TITLE
Couldn't make it work with z3

### ISSUE THREAD

**Issue by zhenyu-zhou** [psycopaths/jdart#2]
Hello,

I encountered a problem when trying to install jdart, could you please help me? I guess the problem should be configuration for z3.

In more detail, I fetched new repositories for jdart (https://github.com/psycopaths/jdart),  z3(https://github.com/Z3Prover/z3) and jconstraints-z3 (https://github.com/psycopaths/jConstraints-z3) by git. I already have a compiled jpf-core version 8. My java version is 8 as well.

The `ant` command at folder jdart/ works well. So do the commands to build z3 (including `make install` and `mvn install:install-file -Dfile=com.microsoft.z3.jar -DgroupId=com.microsoft -DartifactId=z3 -Dversion=0.9 -Dpackaging=jar`). But for jconstraints-z3, I get the following error msg for `mvn install`:
[INFO] Building jConstraints-z3 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for gov.nasa:jconstraints:jar:0.9.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

Therefore, I have to put jconstraints-0.9.1-SNAPSHOT.jar from jdart/lib/ and com.microsoft.z3.jar from z3/build into ~/.jconstraints/extensions as makeshift. After that, I add these two .jar into jpf-jdart.native_classpath inside jpf.properties of jdart/:
jpf-jdart.native_classpath=\
....................................
  ${jpf-jdart}/build/jpf-jdart-annotations.jar;\
  /home/zzy/.jconstraints/extensions/com.microsoft.z3.jar;\
  /home/zzy/.jconstraints/extensions/jconstraints-0.9.1-SNAPSHOT.jar

and add jdart into ~/.jpf/site.properties:
jpf.home=/home/zzy/jpf
jpf-core=${jpf.home}/jpf-core
extensions=${jpf-core}
jpf-jdart=${jpf.home}/jdart
extensions+=,${jpf-jdart}

However, when I tried to run `../jpf-core/bin/jpf src/examples/features/simple/test_foo.jpf` (the file path is slightly different from README because the one in README does not exist) inside the folder jdart/, I got the following error:
JPF configuration error: error instantiating class gov.nasa.jpf.jdart.JDart for entry "shell":

> exception in gov.nasa.jpf.jdart.JDart(gov.nasa.jpf.Config):
> 
> > java.lang.IllegalArgumentException: 'z3' does not denote a valid constraint solver (provider)

Do I miss anything here? I'm a little confused where jdart looks for z3 so that I seems to not put it at proper places.

One thing I noticed here is that I didn't set JVM_ARGS (but how?....). Because I have no access to jConstraints (https://bitbucket.org/psycopaths/jconstraints) and have no idea what happens there. I'm sorry that I still couldn't understand the relationship between z3, jconstraints-z3 and jconstraints well so far.

My folder structure is like:
~/jpf$ pwd
/home/zzy/jpf
~/jpf$ ls
jconstraints-z3        jpf-core       z3       jdart 

Thanks in advance!

**Comment by ksluckow** [comment]
Hi!

Thanks for posting this issue -- I realize that the installation instructions are not very clear. Let me try to clarify here as a quick fix to make it work for you. I will update the READMEs asap.

jConstraints is a solver abstraction layer, and jConstraints-z3 is one of its many plugins. JDart interacts with jConstraints and the configuration specifies which solver backend is used at runtime. Hence you will need to first install jConstraints before attempting to build jConstraints-z3.
The jConstraints repository is: https://github.com/psycopaths/jconstraints
After cloning it, you need to build and install it to your local maven repo:
`mvn install`
That's it! No configuration required :)

After that, you can clone the jConstraints-z3 plugin and install it. Assuming that you built Z3 and its Java bindings and performed the installation according to https://github.com/psycopaths/jconstraints-z3, it can simply be installed by `mvn install`.

Now, jConstraints automatically loads all jConstraints plugins in `$HOME/.jconstraints/extensions`. That folder should contain the plugin and **all** its dependencies. It seems you did this correctly by also copying/symlinking `com.microsoft.z3.jar` in there. Besides those two jars (and assuming you are only interested in Z3 support for now), the extensions folder should not contain anything else. 

If you didn't already, you should also update your `LD_LIBRARY_PATH` (`DYLD_LIBRARY_PATH` for OS X) env variable to point to the location of the Z3 libraries. Otherwise, you will get `UnsatisfiedLinkError` exceptions.

A couple of comments:
- You should not update JPF's native library path in `jdart/jpf.properties`. Whenever a new jConstraints plugin is installed it **only** amounts to place them in the `extensions` folder. No configuration required.
- You correctly set the `jpf-jdart` property in the `site.properties`file, but you should leave the `extensions` property as is (i.e. remove `extensions+=,${jpf-jdart}`) -- it is unnecessary for JDart and is in general not a good idea.

Let me know how it goes.

Thanks again!
Kasper Luckow

**Comment by zhenyu-zhou** [comment]
Hello again!

Thank you so much for your help and now it works! At least for the test case Input.java.

I find I made the following mistakes besides the one you already pointed out (eg. not set `LD_LIBRARY_PATH`):
1. Not install jConstraints. The link in README (https://github.com/psycopaths/jConstraints-z3, first line) seems to be a private one so that I give up to fetch it. Thanks for providing the github repo.
2. I put `jconstraints-0.9.1-SNAPSHOT.jar` rather than `jConstraints-z3-1.0-SNAPSHOT.jar` into `~/.jconstraints/extensions/`. Perhaps there is a typo in README (the same one as 1.) here: " the **jConstraints-z3** library can be found in the JAR file target/**jconstraints-[VERSION].jar**".

And after fixing these issues, it works for me.

Thanks again!
Zhenyu

**Comment by ksluckow** [comment]
Zhenyu,

Great you got it working! I'll work on the documentation this week to clarify and fix the flaws you correctly mention do not reflect the current state of the components. Thanks!

Kasper
