### ISSUE TITLE
Class not found gov.nasa.jpf.jdart.JDart by classloader

### ISSUE THREAD

**Issue by MarwenSami** [psycopaths/jdart#5]
Hello,
When I try to run JPF as shown in the "Using JDart" section, I get a JPF configuration error:

> Exception in thread "main" ---------------------- JPF error stack trace ---------------------
> JPF configuration error: class not found gov.nasa.jpf.jdart.JDart by classloader: gov.nasa.jpf.JPFClassLoader@5c647e05
>   at gov.nasa.jpf.Config.asClass(Config.java:1667)
>   at gov.nasa.jpf.Config.getClass(Config.java:1691)
>   at gov.nasa.jpf.Config.getInstance(Config.java:1885)
>   at gov.nasa.jpf.Config.getInstance(Config.java:1880)
>   at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:106)

I followed all the required steps in the README.md.
However, if I add ${jpf-jdart} in the extensions property in site.properties file, I pass beyond this error and the shell is loaded (Another error class not found error related to opt4j is generated).

I'm confuzed about this issue, did I do wrong the configuration part ? is it ok if I add jDart to extensions property ?

Best regards,

**Comment by ksluckow** [comment]
Hi,
Can you post the contents of your application jpf file? I suppose you defined the `jpf-jdart` variable in the site.properties file, but in order to use it, you can either add id to the extensions variable in site.propertis as you did **or** set `@using = jpf-jdart` in your application jpf file (see `src/examples/features/simple/using.jpf`). I encourage to use the `@using` directive method, since otherwise, all the jdart classes are added to the global classpath for jpf.
I see that the installation instructions are a bit unclear regarding this, so I'll update it today.

**Comment by MarwenSami** [comment]
Hello,
Thank you for the quick reply.
Yes I did define jpf-jdart variable as ${user.home}/Desktop/JDart/jdart.
indeed I forgot to add @using = jpf-jdart to the jpf file, I modified the file and I get a new error : 

> Exception in thread "main" ---------------------- JPF error stack trace ---------------------
> JPF configuration error: error instantiating class gov.nasa.jpf.jdart.JDart for entry "shell":
> 
> > exception in gov.nasa.jpf.jdart.JDart(gov.nasa.jpf.Config):
> > 
> > > java.lang.NoClassDefFoundError: org/opt4j/optimizer/mopso/MOPSOModule
> > >   at gov.nasa.jpf.Config.getInstance(Config.java:2015)
> > >   at gov.nasa.jpf.Config.getInstance(Config.java:1889)
> > >   at gov.nasa.jpf.Config.getInstance(Config.java:1880)
> > >   at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:106)

I checked that the opt4j.jar is referenced in the build path of JDart project.

(Solved Thank you anyway)

**Comment by ksluckow** [comment]
Good to hear it's working :)
Opt4j is not directly a dependency to jdart. However, it is a transitive dependency if you are using the Coral solver plugin for jConstraints. Is this the case? Or maybe you are building an analysis on top of jdart? In any case, have you tried adding it to the (runtime) classpath?

**Comment by MarwenSami** [comment]
Well I'm using Coral as solver plugin, and I solved the issue by adding Opt4j to the .jconstraints\extensions folder, Howerver I don't think that the solver is working correctly as I encounter another NoClassDefFoundError when trying to run any of the .jpf examples.
The issue is: 

> java.lang.NoClassDefFoundError: org/apache/commons/math/random/RandomDataImpl
>   at coral.solvers.rand.NumberGenerator.<init>(NumberGenerator.java:43)
>   at coral.solvers.search.opt4j.ctp.CTP_Module.<init>(CTP_Module.java:29)
>   at coral.solvers.search.opt4j.pso.PSOSolver_Module.<init>(PSOSolver_Module.java:17)
>   at coral.solvers.search.opt4j.pso.PSOSolver.call(PSOSolver.java:71)
>   at coral.solvers.search.opt4j.pso.PSOSolver.call(PSOSolver.java:243)
>   at coral.solvers.Solver.call(Solver.java:241)
>   at coral.solvers.Solver$1.call(Solver.java:100)
>   at coral.solvers.Solver$1.call(Solver.java:1)

it's obvious that the solver can't find org.apache.commons.math, I did download the package from the apache official website however the package name is org/apache/commons/math3 instead of org/apache/commons/math.

**Comment by ksluckow** [comment]
The coral solver is quite messy and classpath problems seem inevitable notably because---if I remember correctly---it redefines some library classes in opt4j.
You can probably fix it by adding the dependencies to the native classpath either in the `jpf.properties` file or in the application jpf file. If the problem persists, you should open an issue for [jconstraints-coral](https://github.com/psycopaths/jconstraints-coral) :)

**Comment by chafay** [comment]
you must run it in jdart folder into cmd : 
1/  cd /path/to/jdart  
2/  /path/to/jpf-core/bin/jpf /path/to/jdart/src/examples/features/simple/test_foo.jpf

**Comment by ksluckow** [comment]
Yes, this applies to any JPF extension.
