### ISSUE TITLE
JDart on JavaCard ?

### ISSUE THREAD

**Issue by MarwenSami** [psycopaths/jdart#6]
Hello,
I want to know if it's possible to work with JDart on JavaCard ?
Is it possible to add javacard framework to JPF virtual machine ?

**Comment by ksluckow** [comment]
Frankly, I only have very limited experience with JavaCard, but I understand it is a proper subset of the JVM. That's good. 
The problem is that it seems that the bytecode encoding is slightly different from the JVM, therefore I don't think it will work if you only have the compiled framework.
The exception would be if Java PathFinder has support for the JavaCard VM. As far as I know that is not the case, but I might be wrong.

I don't know much about the framework for JavaCard (do you mean the class library?), but if you are able to compile it yourself, maybe you can target the standard jvm and do the same with the SUT. In that case JDart should work as with any other program that runs on the jvm.

**Comment by MarwenSami** [comment]
Yes, I'm working on recompiling the JavaCard class library, so far it seems possible to make it work on JPF VM.

**Comment by Bareuzai** [comment]
I worke with Marouan on Java Card. there is something that I do not understand. In this example:
@Symbolic ("true")  byte state =0;
@Symbolic ("true")  int stateInt =0;
@Symbolic ("true")    byte[] stateA = {1,2};
public void bar(byte[] ba){
        if(ba[0] == 50){
            ba[1] = 1;  state = 10;    // primitive state variables
            stateInt = 100; stateA[1] =5; } // array state variables
        }
This method is configured as concoloc with its parameters. Jdart finds two inputs
[INFO] -((sint32)'ba[0]' != 50)
  |-[+]_/OK: [ ba[1]:='ba[1]', ba[0]:='ba[0]', this.stateA[0]:='this.stateA[0]', this.stateA[1]:='this.stateA[1]', this.stateInt:='this.stateInt', this.state:='this.state',  ]
  +-[-]_/OK: [ ba[1]:='ba[1]', ba[0]:='ba[0]', this.stateA[0]:='this.stateA[0]', this.stateA[1]:='this.stateA[1]', this.stateInt:=100, this.state:=10,  ]

If ba[0] is different from 50, state variables remain unchanged and if ba[0] equals 50 then SOME state variable are changed: state and stateInt while the arrays ba[] and stateA[] are unchanged. I do not understand this process.

**Comment by ksluckow** [comment]
I'll have to investigate this further, but I don't have time atm. However, it seems that it may only be related to the constraints tree representation of (possibly only) array elements, because the valuations are correct on my machine (first valuation corresponds to the initial assignment to `ba[]`):

```
[INFO:jdart] -------Valuation Statistics-------
[INFO:jdart] # of valuations (OK+ERR): 2
[INFO:jdart] 
[INFO:jdart] java.lang.Byte:ba[1]=2, java.lang.Byte:ba[0]=1, 
[INFO:jdart] java.lang.Byte:ba[1]=0, java.lang.Byte:ba[0]=50, 
[INFO:jdart] --------------------------------
```

**Comment by MarwenSami** [comment]
Hello,
Yes the valuations are correct ! but the final state of array elements isn't outputed correctly.

**Comment by ksluckow** [comment]
Yeah, I will look into fixing the output asap.

**Comment by symbolic** [comment]
Hi, everyone, I am @symbolic.
So I received this notification

**Comment by anboua** [comment]
I want to know the meaning of @Symbolic ("true") before the variable ??

**Comment by ksluckow** [comment]
The annotation is used to specify whether the field should be treated as a symbolic variable. Check out the example `src/examples/globals/Input.java`.

**Comment by anboua** [comment]
Thank you...,
Can you tell me which fields must be annotated in JDart

**Comment by ksluckow** [comment]
That is up to the user: the idea of symbolic analysis is that the user specifies which variables should be treated as _symbolic_ instead of _concrete_. Symbolic variables can be injected through method parameters and fields.

**Comment by anboua** [comment]
@MarwenSami  
it is possible to test javacard on JDart ?

**Comment by MarwenSami** [comment]
We are actually working on it, you need to integrate the JavaCard API into JPF.
